---
title: Dr Josh Tyler
email: Joshua.Tyler1993(at)gmail(dot)com
description: Postdoc at the Turing Institute working on Probabilistic
  Programming and its applications in Evolution, Biodiversity & Health.
baseurl: ""
url: ""
twitter_username: joshtylerearth
github_username: JTyler13
remote_theme: pages-themes/cayman@v0.2.0
plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
header_pages:
 - about.md
 - papers.md
 - CV.md
