---
title: Dr Josh Tyler
email: Joshua.Tyler1993(at)gmail(dot)com
description: Postdoc at the Turing Institute working on Probabilistic
  Programming and its applications in Evolution, Biodiversity & Health.
baseurl: ""
url: ""
twitter_username: joshtylerearth
github_username: JTyler13
theme: minima
plugins:
  - jekyll-feed
header_pages:
 - about.md
 - papers.md
 - CV.md
