---
title: Dr Josh Tyler
email: Joshua.Tyler1993(at)gmail(dot)com
description: Postdoc at the Turing Institute working on Probabilistic
  Programming and its applications in Evolution, Biodiversity & Health.
baseurl: ""
url: ""
twitter_username: joshtylerearth
github_username: JTyler13
# theme: minima
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme