project:
  type: website
  output-dir: docs

website:
  title: "Dr Josh Tyler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - papers.qmd
      - CV.qmd
  page-footer:
    border: true
    left: "Postdoc at the Turing Institute working on Probabilistic
  Programming and its applications in Evolution, Biodiversity & Health."
    center:
      - icon: twitter
        href: https://twitter.com/JoshTylerEarth
        aria-label: Twitter
      - icon: github
        href: https://github.com/jtyler13
        aria-label: GitHub


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual