project:
  type: website
  output-dir: docs

website:
  title: "Dr Josh Tyler"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - papers.qmd
      - CV.qmd
  page-footer:
    border: true
    center:
      - text: "Postdoc at the Turing Institute working on Probabilistic Programming and its applications in Evolution, Biodiversity & Health."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual