project:
  type: website
  output-dir: docs

website:
  favicon: images/favicon.png
  title: "Dr Josh Tyler"
  navbar:
    title: "Dr Josh Tyler"
    logo: images/favicon.png
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
      - papers.qmd
      - CV.qmd
  page-footer:
    border: true
    left: Copyright 2024 - Josh Tyler
    right:
      - text: "Probabilistic Programming and its applications in Evolution, Biodiversity & Health"

format:
  html:
    theme:
      light: minty
    css: styles.css
    toc: false
    page-layout: full

editor: source