project:
  type: website
  output-dir: docs

website:
  favicon: images/favicon.png
  title: "Dr Josh Tyler"
  navbar:
    title: "Dr Josh Tyler"
    logo: images/favicon.png
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: papers.qmd
        text: Publications
      - href: CV.qmd
        text: CV & Experience
  page-footer:
    border: true
    left: Copyright 2026 - Josh Tyler
    right:
      - text: "Interdisciplinary Researcher in Data Science"

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    page-layout: full

editor: source
