project:
  type: website
  output-dir: _site

website:
  favicon: images/favicon.png
  title: "Dr Josh Tyler"
  navbar:
    title: "Dr Josh Tyler"
    logo: images/favicon.png
    right:
      - href: index.qmd
        text: Home
      - papers.qmd
      - CV.qmd
      - blog.qmd
  page-footer:
    border: true
    left: Copyright 2024 - Josh Tyler
    right:
      - text: "Probabilistic Programming and its applications in Evolution, Biodiversity & Health"

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: false

editor: visual