---
title: "CV"
toc: true
---

# Education

**PhD in Biology, Milner Centre for Evolution, University of Bath, UK** *2019 – 2023*

-   Thesis: Phylogenetic Diversity, Morphological Disparity & Niche Adaptation in Seabirds

-   Supervisors: Professor Matt Wills & Dr Nick Priest (Milner Centre for Evolution, University of Bath) and Dr Jane Younger (University of Tasmania)

-   Key Techniques: Advanced Analysis in R, Linear & Geometric Morphometrics, Phylogenetic Comparative Methods, Discrete Character Evolution, Species Delimitation Techniques.

**Master of Earth Sciences, Exeter College, University of Oxford, UK** *2011 – 2015*

-   Degree & Classification: MEarthSci – 2.i

-   Masters Thesis: “The battle for the Mesozoic skies: Studying competition as a driver of macroevolution in pterosaurs” (Supervisor: Prof R Benson, First Class)

-   Fieldwork Locations: Pembrokeshire, Arran, Dorset, Assynt, Corsica, Almeria/Carboneras (SE Spain), Bermuda.

------------------------------------------------------------------------

# Research Appointments

**Research Associate in Probabilistic Programming at the Turing Institute** *September 2024-Present*

-   Focus on building a UK Probabilistic Programming Community around Biodiversity, Health and Climate.

-   Leading research into the applications of PGLMMs to ecological and evolutionary questions.

**Senior Consultant, Strategic Analytics, AtkinsRèalis, Bristol** *March 2023 - September 2024*

-   Focus on developing and delivering innovative and novel data-driven solutions to client problems.

-   Capability lead for Data-Driven Decision-Making and creating analytical resources in R.

**Simulation Modelling Specialist: Modelling & Analytics, NHS, Bristol** *January 2019 - September 2019 & November 2020 – June 2021*

-   Project: Developing a versatile tool for modelling pathway capacity in NHS organisations

-   Project Overview: The Health Foundation-funded project involved building an analytical tool and UI in R that could model several interconnected health services along a given patient pathway using techniques from queueing theory and operational research.

-   Tool Link: <https://github.com/nhs-bnssg-analytics/PathSimR>

**Research Assistant: Museum fur Naturkunde, Berlin** *August 2016 - December 2018*

-   Project: Herbivore Niche Differentiation and the Intensification of Competition in African Savannahs

-   Project Overview: The DFG-funded project sought to trace the evolution of niche partitioning and competitive interaction across Bovidae (Antelope & their relatives) on the African Savannah from their origins through to the Recent.

------------------------------------------------------------------------

# Teaching

-   PGLMMs for Biodiversity Modelling Workshop - StanCon (2024)


------------------------------------------------------------------------

# Grants & Awards

-   Research Grant (£20,000 Consumable Grant) - Royal Society London (2021)
-   Visiting Research Scholarship (\$3900 Travel Grant) - Chicago Field Museum (2020)
-   Future Research Leaders Grant (£2509 Travel Grant) - University of Bath (2019)
-   Evolution Education Trust PhD Studentship (Stipend, Fees & Research Costs) - University of Bath (2019)

------------------------------------------------------------------------

# Conference Presentations

-   Janis C, Franklin G, Baird CN & **Tyler J**. The radiation of Miocene Anchitheres: the forgotten large browsing Horses. SVPCA; Online. Poster 2021
-   **Tyler J** & Younger J. Morphometric and genetic evidence for four species of gentoo penguin. Evolution; Online. Talk, 2021
-   **Tyler J** & Younger J. Hidden biodiversity in gentoo penguins. Biology & Biochemistry Research Symposium; University of Bath. Poster, 2020
-   **Tyler J** & Bibi F. Investigating niche evolution using skull morphology in modern antelope (Bovidae) communities. Evolution; Montpellier, France. Poster, 2018
-   **Tyler J** & Bibi F. Investigating the role of competition and biotic interaction on the evolution of African bovids: A geometric morphometric & phylogenetic approach. IPC; Paris, France. Talk, 2018

------------------------------------------------------------------------

# Invited Seminars

-   Institute for Marine & Antarctic Studies, University of Tasmania – *August 2022* - Diversity, Disparity & Dead-Ends? Macroevolutionary patterns in Waterbirds.
-   Bristol Naturalists’ Society – *March 2021* - Spot the difference! Understanding morphological variation in birds and the implications for cryptic species.
-   Milner Centre for Evolution – *March 2021* – Hidden biodiversity in Gentoo penguins and other avian morphometric mysteries.

------------------------------------------------------------------------

# Media Coverage

-   Hidden biodiversity in gentoos – [Naked Scientists Podcast Interview](https://www.thenakedscientists.com/articles/interviews/gentoo-penguins-three-hidden-species-discovered), [Ecology & Evolution Blog](https://ecologyandevolutionblog.wordpress.com/2020/11/06/hidden-biodiversity-in-gentoo-penguins/), [BBC News](https://www.bbc.co.uk/news/science-environment-54817124#:~:text=Scientists%20are%20calling%20for%20a,told%20apart%20by%20their%20DNA.), [Conversation Article](https://theconversation.com/how-we-discovered-three-new-species-of-penguin-in-the-southern-ocean-149325). Estimated reach: 531 million.
-   Albatross Bill Shape – [Conversation Article](https://theconversation.com/thick-ones-pointy-ones-how-albatross-beaks-evolved-to-match-their-prey-211461)

------------------------------------------------------------------------

# Student Supervision

**BA Biology Project Co-Supervisor (PI: Dr. Jane Younger). University of Bath, Bath, UK.**

*Morphological Variation in Spheniscidae Skeletal Elements*

Students: Jack Hardy (21/22), Sam Jones (21/22), Harley Mitchell (21/22)

*Phylogeography & Cryptic Species in Malagasy Birds*

Students: Georgina Russell (19/20), Louis Martin (20/21), Nefeli Karonis (20/21)

**MSc Bioinformatics Project Co-Supervisor (PI: Dr. Nick Priest). University of Bath, Bath, UK.**

*Understanding Global Patterns of Biodiversity and Diversification in Fungi*

Students: Gabriel Crabb (21/22), Enea Jorgji (21/22)

**MSci Palaeobiology Thesis Co-Supervisor (PI: Prof Christine Janis). University of Bristol, Bristol, UK.**

*Locomotor evolution in horses: divergence between anchitheres and equines*

Students: Gwen Franklin (20/21)

------------------------------------------------------------------------

# Engagement Activities & Widening Participation

-   Evolution Conference Undergraduate Mentor. Online. 2021
-   Global Science Show & Futures 2020. Online. 2020
-   Morphometrics & Macroevolution Journal Club. University of Bath, Bath, UK. 2019-2023
-   Gold Scholarship Programme Mentor. University of Bath, Bath, UK. 2019-2022

------------------------------------------------------------------------

# Workshops & Professional Development

-   Statistical Rethinking. Course on Bayesian Data Analysis and Causal Inference. Online 2023
-   SVPCA Workshop 1: 3D data, FAIR principles and Morphosource. University of Oxford, UK. 2021
-   Public Engagement with Science Workshop. Royal Society, UK. 2020
-   Phylogenetics in Evolution and Ecology Course. Natural History Museum, Berlin, Germany. 2018
