---
title: "Publications & Outputs"
toc: true
---

# PhD Thesis

::: {.publications-list}
-   **Tyler, J.** (2023). *Phylogenetic Diversity, Morphological Disparity and Niche Adaptation in Seabirds*. University of Bath. [[PDF](files/PhD_Thesis.pdf)]
:::

# Evolution & Ecology Publications

<ol class="publications-list" start="1">
  <li>**Tyler, J.**, Hocking, D. & Younger, J. (2023). Intrinsic & extrinsic drivers of shape variation in the Albatross compound bill. *Royal Society Open Science*, 10: 230751. [[DOI](https://doi.org/10.1098/rsos.230751)]</li>
  <li>**Tyler, J.** & Younger, J. (2023). How we found three new species of penguins. *Frontiers for Young Minds - Biodiversity*. [[DOI](https://doi.org/10.3389/frym.2023.1044850)]</li>
  <li>Janis, C.M., Franklin, E., Baird, C.N. & **Tyler, J.** (2023). The Miocene Browsing Horses: Another Way to Be a Successful Large Equid. In: Prins, H.H.T., Gordon, I.J. (eds) *The Equids. Fascinating Life Sciences*. Springer, Cham. [[DOI](https://doi.org/10.1007/978-3-031-27144-1_3)]</li>
  <li>**Tyler, J.** & Younger, J. (2022). Diving into a dead-end: Asymmetric evolution of diving drives diversity and disparity shifts in Waterbirds. *Proceedings of the Royal Society B*, 289: 20222056. [[DOI](https://doi.org/10.1098/rspb.2022.2056)]</li>
  <li>Bibi, F. & **Tyler, J.** (2022). Evolution of the bovid cranium: Morphological diversification under allometric constraint. *Communications Biology*, 5: 69. [[DOI](https://doi.org/10.1038/s42003-021-02877-6)]</li>
  <li>**Tyler, J.**, Bonfitto, M.T., Clucas, G.V., Reddy, S. & Younger, J.L. (2020). Morphometric and genetic evidence for four species of gentoo penguin. *Ecology and Evolution*, 10: 13836–13846. [[DOI](https://doi.org/10.1002/ece3.6973)] | [[Altmetric Summary](https://bit.ly/3aLmUpJ)]</li>
</ol>

# Healthcare Simulation & Modelling Publications

<ol class="publications-list" start="7">
  <li>**Tyler, J.**, Murch, B.J., Vasilakis, C. & Wood, R.M. (2022). Improving uptake of simulation in healthcare: User-driven development of an open-source tool for modelling patient flow. *Journal of Simulation*, 17: 1-18. [[DOI](https://doi.org/10.1080/17477778.2022.2081521)]</li>
  <li>**Tyler, J.**, Pratt, A.C., Wooster, J., Vasilakis, C. & Wood, R.M. (2021). The impact of increased outpatient telehealth during COVID-19: Retrospective analysis of patient survey and routine activity data from a major healthcare system in England. *International Journal of Health Planning and Management*, 36: 1338-1345. [[DOI](https://doi.org/10.1002/hpm.3185)]</li>
  <li>Wood, R.M., Murch, B.J., Moss, S.J., **Tyler, J.**, Thompson, A.L. & Vasilakis, C. (2021). Operational research for the safe and effective design of COVID-19 mass vaccination centres. *Vaccine*, 39: 3537-3540. [[DOI](https://doi.org/10.1016/j.vaccine.2021.05.024)]</li>
</ol>

# Selected Talks & Invited Seminars

::: {.publications-list}
-   **Institute for Marine & Antarctic Studies**, University of Tasmania (Aug 2022) | *Diversity, Disparity & Dead-Ends? Macroevolutionary patterns in Waterbirds.*
-   **Bristol Naturalists’ Society** (Mar 2021) | *Spot the difference! Understanding morphological variation in birds and the implications for cryptic species.*
-   **Milner Centre for Evolution** (Mar 2021) | *Hidden biodiversity in Gentoo penguins and other avian morphometric mysteries.*
-   **Evolution Conference** (Online, 2021) | *Morphometric and genetic evidence for four species of gentoo penguin.* (Talk)
-   **IPC**, Paris, France (2018) | *Investigating the role of competition and biotic interaction on the evolution of African bovids.* (Talk)
:::

# Media Coverage & Public Engagement

::: {.publications-list}
-   **Gentoo Penguin Species Discovery:** Covered by BBC News, the Naked Scientists Podcast, Ecology & Evolution Blog, and featured in a Conversation Article.
-   **Albatross Bill Shape Evolution:** Featured in a Conversation Article.
-   **Penguin Research Feature:** Interviewed on *Midnight Meets with Colin Murray* (BBC Radio 5 Live).
:::
